CREATE TABLE TAB_USER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(255),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR (100)
    CV VARCHAR (100)

);

CREATE TABLE TAB_CURRICULUM(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID INTEGER REFERENCES TAB_USER(ID),
    NOME VARCHAR(100),
    TELEFONE VARCHAR(100),
    EMAILCONTATOCV VARCHAR(100),
    SOBRE VARCHAR(255)
);

CREATE TABLE TAB_EXPERIENCIA(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    EXPERIENCIA_CURRICULUM_ID INTEGER REFERENCES TAB_CURRICULUM(ID),
    EXPERIENCIA VARCHAR(255)
);

CREATE TABLE TAB_QUALIFICACAO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    QUALIFICACAO_CURRICULUM_ID INTEGER REFERENCES TAB_CURRICULUM(ID),
    QUALIFICACAO VARCHAR(255)
);
